# Generated by Django 4.2.6 on 2023-11-27 12:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Nome')),
                ('description', models.TextField(default='', max_length=250, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagem')),
                ('sound', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Amostra de Áudio')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=14, unique=True, verbose_name='Matrícula')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.CharField(default='', max_length=250, verbose_name='Justificativa')),
                ('justify_status', models.CharField(default='Ainda não justificado.', max_length=250, verbose_name='Justificativa Status')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('entry_hour', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de Entrada')),
                ('exit_hour', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de Saída')),
                ('post', models.DateTimeField(auto_now=True, verbose_name='Post')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.perfil', verbose_name='Perfil')),
                ('status', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='status', to='reserva.status', verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150, verbose_name='Título')),
                ('text', models.TextField(default='', verbose_name='Texto')),
                ('image', models.ImageField(upload_to='', verbose_name='Imagem')),
                ('post', models.DateTimeField(auto_now=True, verbose_name='Post')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.perfil', verbose_name='Autor')),
            ],
        ),
    ]
