# Generated by Django 4.2.6 on 2023-10-28 18:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=14, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.CharField(default='', max_length=250, verbose_name='Justificativa')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('entry_hour', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de Entrada')),
                ('exit_hour', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de Saída')),
                ('post', models.DateTimeField(auto_now=True, verbose_name='Post')),
                ('status', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='status', to='reserva.status', verbose_name='Status')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.perfil', verbose_name='Usuário')),
            ],
        ),
    ]
