# Generated by Django 4.2.4 on 2023-10-14 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='matricula',
        ),
    ]
