# Generated by Django 4.1.3 on 2023-10-23 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_perfil_profilepic_alter_perfil_matricula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='profilePic',
        ),
    ]
