# Generated by Django 4.2.6 on 2023-10-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_remove_perfil_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='post',
            field=models.DateTimeField(auto_now=True, verbose_name='Post'),
        ),
    ]
