# Generated by Django 4.2.6 on 2023-10-26 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_alter_solicitacao_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='data',
            field=models.DateField(default=datetime.date.today, verbose_name='Data'),
        ),
    ]
