# Generated by Django 4.2.4 on 2023-10-01 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0002_remove_solicitacao_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='matricula',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='solicitacao.perfil'),
            preserve_default=False,
        ),
    ]
