# Generated by Django 4.2.4 on 2023-10-02 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0003_solicitacao_matricula_solicitacao_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacao.perfil'),
        ),
    ]
