# Generated by Django 4.2.4 on 2023-10-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0004_alter_solicitacao_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='justificativa',
            field=models.TextField(default='', max_length=250, verbose_name='Justificativa'),
        ),
    ]
