# Generated by Django 4.2.4 on 2023-10-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0005_alter_solicitacao_justificativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='justificativa',
            field=models.CharField(default='', max_length=250, verbose_name='Justificativa'),
        ),
    ]
